# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('typ', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Playlist'), (1, 'Channel')], null=True)),
            ],
            options={
                'verbose_name': 'Content Source',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=400)),
                ('duration', models.DurationField()),
                ('views_count', models.PositiveIntegerField()),
                ('thmubnail', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.Source')),
            ],
        ),
    ]
