# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='youtube_id',
            field=models.CharField(default=11, max_length=150),
            preserve_default=False,
        ),
    ]
