# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_source_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='thmubnail',
            field=models.URLField(),
        ),
    ]
