# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170319_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(editable=False, max_length=70, primary_key=True, serialize=False),
        ),
    ]
