# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170320_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thmubnail',
            new_name='thumbnail',
        ),
    ]
